---
  - name: Create directory structure
    win_file:
      path: C:\bakup base
      state: directory
  - name: Copy a single file keeping the filename
    win_copy:
      src: /root/wiki/files/database.sql
      dest: C:\bakup base\databakup.sql
  - name: restore backup base
    win_command: powershell.exe -
    args:
      stdin: pg_dump -U postgres wiki < "C:\bakup base\databakup.sql"
    become: True
    become_method: runas
    vars:
      ansible_become_user: postgres
      ansible_become_pass: "Mzayech@1986"
